In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

### Create & Read

#### 1D Array

In [9]:
arr1=np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

In [10]:
arr1.size

6

### 2D Arraey

In [11]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim

2

In [14]:
arr2.shape # (row, col)

(2, 4)

In [15]:
arr2.dtype

dtype('int64')

In [16]:
arr2.size

8

### 3D Array

In [2]:
arr3=np.array([[[1,4,5],[6,7,8]],[[3,5,4],[5,8,7]],[[1,4,5],[6,7,4]]])

In [3]:
arr3

array([[[1, 4, 5],
        [6, 7, 8]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [20]:
arr3.ndim

3

In [21]:
arr3.shape

(3, 2, 3)

In [22]:
arr3.size

18

### Create Random Array

In [23]:
randomarr=np.random.rand(3,2,3)

In [24]:
randomarr

array([[[0.96987698, 0.02357321, 0.94998397],
        [0.32295476, 0.29148222, 0.11859079]],

       [[0.34685442, 0.002369  , 0.09710517],
        [0.80162681, 0.35420154, 0.28164962]],

       [[0.0654521 , 0.95941264, 0.25302666],
        [0.07483402, 0.27474053, 0.18689477]]])

In [25]:
randomarr.dtype

dtype('float64')

In [27]:
zeroes=np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
arr3

array([[[1, 4, 5],
        [6, 7, 8]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [10]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 8]])

In [12]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 8]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [13]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [14]:
arr3[1][0][1]

np.int64(5)

In [15]:
arr3[1, 0, 1]

np.int64(5)

### Update & Delete

In [4]:
a1=np.random.rand(2, 3, 2)
a2=np.random.rand(2, 3, 2)

In [5]:
a1

array([[[0.41370862, 0.48872097],
        [0.01939642, 0.29142446],
        [0.58155534, 0.23180838]],

       [[0.02666299, 0.89643017],
        [0.80999452, 0.5569832 ],
        [0.81938144, 0.35227974]]])

In [6]:
a2

array([[[0.33465293, 0.45581429],
        [0.50692188, 0.78287678],
        [0.16397346, 0.64123747]],

       [[0.22992551, 0.26677455],
        [0.20275588, 0.36975162],
        [0.07064899, 0.65024383]]])

#### Basic Math Operations

In [7]:
np.add(a1, a2)

array([[[0.74836155, 0.94453527],
        [0.5263183 , 1.07430124],
        [0.74552879, 0.87304584]],

       [[0.2565885 , 1.16320473],
        [1.0127504 , 0.92673483],
        [0.89003043, 1.00252357]]])

In [8]:
np.subtract(a1, a2)

array([[[ 0.0790557 ,  0.03290668],
        [-0.48752547, -0.49145231],
        [ 0.41758188, -0.40942909]],

       [[-0.20326252,  0.62965562],
        [ 0.60723864,  0.18723158],
        [ 0.74873245, -0.29796409]]])

In [9]:
np.divide(a1, a2)

array([[[ 1.2362319 ,  1.07219317],
        [ 0.03826313,  0.37224819],
        [ 3.54664316,  0.36150161]],

       [[ 0.11596359,  3.36025369],
        [ 3.99492494,  1.50637122],
        [11.59792123,  0.54176561]]])

In [10]:
np.multiply(a1, a2)

array([[[0.1384488 , 0.22276601],
        [0.00983247, 0.22814945],
        [0.09535964, 0.14864422]],

       [[0.0061305 , 0.23914476],
        [0.16423115, 0.20594544],
        [0.05788847, 0.22906773]]])

#### STATISTICAL OPERATION

In [16]:
sqrt=np.sqrt(25)
abs=np.abs(-2)
power=np.power(2,8)
log=np.log(25)
mins=np.min(a1)
maxs=np.max(a2)

In [12]:
sqrt

np.float64(5.0)

In [13]:
abs

np.int64(2)

In [14]:
power

np.int64(256)

In [17]:
log

np.float64(3.2188758248682006)

In [18]:
mins

np.float64(0.019396416444292797)

In [19]:
maxs

np.float64(0.7828767773632264)

#### Update

In [20]:
arr3

array([[[1, 4, 5],
        [6, 7, 8]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [21]:
arr3[0,0,2]=500
arr3

array([[[  1,   4, 500],
        [  6,   7,   8]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [22]:
arr3.sort()

In [23]:
arr3

array([[[  1,   4, 500],
        [  6,   7,   8]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

#### Reshape

In [24]:
arr3.shape

(3, 2, 3)

In [25]:
arr3_reshape=arr3.reshape((2,3,3))
arr3_reshape

array([[[  1,   4, 500],
        [  6,   7,   8],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

#### Appending & Inserting

In [28]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
# create a new array
new_array=np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [30]:
appd=np.append(zeroes, new_array, axis=0) #axis 0= row, axis 1=column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
appd1=np.append(zeroes, new_array, axis=1) #Axio 0=row, Axis 1=column
appd1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

#####  Insert

In [35]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
inserted_array=np.insert(zeroes, 1, new_array, axis=0)

In [38]:
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [40]:
arr4=np.random.rand(3, 2, 3)

In [41]:
arr4

array([[[0.61152041, 0.18958579, 0.07440721],
        [0.39245115, 0.53697821, 0.28251513]],

       [[0.08436465, 0.325429  , 0.82008914],
        [0.35876124, 0.24304061, 0.84319557]],

       [[0.45567361, 0.64957648, 0.649088  ],
        [0.63828507, 0.33494458, 0.25643431]]])

In [42]:
# Delete the array

arr5=np.delete(arr4, 0, axis=1)

In [43]:
arr5

array([[[0.39245115, 0.53697821, 0.28251513]],

       [[0.35876124, 0.24304061, 0.84319557]],

       [[0.63828507, 0.33494458, 0.25643431]]])

In [44]:
np.save("new_array",arr5)

In [45]:
np.load("new_array,npy")

FileNotFoundError: [Errno 2] No such file or directory: 'new_array,npy'